// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadScores() {
  return window['go']['main']['App']['LoadScores']();
}

export function SaveScores(arg1) {
  return window['go']['main']['App']['SaveScores'](arg1);
}
