// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVersion():Promise<string>;

export function LoadScores():Promise<main.ScoreBoard>;

export function SaveScores(arg1:main.ScoreBoard):Promise<void>;
